name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "2.1.*"
      - run: deno check scripts/*.ts
      - name: Run tests
        run: deno task test
      - name: Run linter
        run: deno lint .
      - name: Run formatter
        run: deno fmt --check
